# -*- coding: utf-8 -*-
"""
Created on Wed May  3 11:33:29 2017

@author: Kirill
"""

send_list = {
	'444838': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.406@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'469135': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.117@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'564162': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.176@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'4151015': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','lv.678@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1944369': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','zt.445@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'628986': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','lv.223@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'922073': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.254@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'937765': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.271@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'564038': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.145@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2507531': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.558@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'943931': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.279@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1546078': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.426@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'446909': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.197@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'447025': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','cn.203@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'446734': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.187@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'470073': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.192@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'446694': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.185@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'445045': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.109@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2133556': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','lv.463@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'446458': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.168@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'444840': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.331@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'947196': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.341@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'565537': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','cn.204@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2345323': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','lv.499@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2507565': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.559@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2507573': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.561@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'3066497': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','if.641@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'3079391': ['biloshicka.t@watsons.ua','kovernyak.s@watsons.ua','kv.632@watsons.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1254426': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'920448': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'972711': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'952328': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'953609': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1449607': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'970899': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1248138': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1545767': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1939671': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'921756': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'946777': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1449600': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1445521': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'947273': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2104943': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2717583': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'1606478': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2919514': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2975320': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2975312': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2963108': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
	'2961750': ['zakaz_site@apteka24.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '941969' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '954215' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '951580' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '996094' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '1504960' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '1018356' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '1018357' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '1123825' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '1157372' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '1260578' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '1260583' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'], 
      '2203177' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'], 
      '946997' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'], 
      '2423454' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'], 
      '2442047' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'], 
      '2436445' : ['reserv@aptekamirra.com.ua', 'a.melnichuk@aptekamirra.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'], 
      '448079':['rezerv5_7@e-apteka.com.ua','ogorodniychuk@e-apteka.com.ua','lytvynenko@e-apteka.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '469112':['rezerv5_7@e-apteka.com.ua','ogorodniychuk@e-apteka.com.ua','lytvynenko@e-apteka.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '471764':['rezerv5_7@e-apteka.com.ua','ogorodniychuk@e-apteka.com.ua','lytvynenko@e-apteka.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '446319':['rezerv5_7@e-apteka.com.ua','ogorodniychuk@e-apteka.com.ua','lytvynenko@e-apteka.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '446320':['rezerv5_7@e-apteka.com.ua','ogorodniychuk@e-apteka.com.ua','lytvynenko@e-apteka.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '469106':['rezerv5_7@e-apteka.com.ua','ogorodniychuk@e-apteka.com.ua','lytvynenko@e-apteka.com.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua'],
      '2469190':['apteka0961241590@yandex.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua','geoapteka.com.ua@gmail.com'],
      '1254757':['apteka0961241590@yandex.ua','natalya.karandasheva@geoapteka.ua','anna.stadnik@proximaresearch.com','geoapteka.com.ua@gmail.com','nadiia.honchar@proximaresearch.com.ua','geoapteka.com.ua@gmail.com']    
}